FROM node:16.14 as build-context-frontend

RUN mkdir /home/frontend
COPY frontend /home/frontend/

WORKDIR /home/frontend/
COPY frontend/package.json /home/frontend/package.json
RUN npm ci
RUN npm run build
RUN cd /home/frontend/
