version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.site
    command: npm run prod
    ports:
      - "4200:3000"
    volumes:
      - ./.dist/site/:/home/site/.dist
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: npm run dev
    ports:
      - "3000:3000"
#  TODO: fix this so that docker-compose up works without local nginx rerouting
#  nginx:
#    image: nginx:1.21.5
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/:/etc/nginx/conf
#      - ./frontend/dist/todo:/usr/share/nginx/html/site/
